package plat:plugin;

world plat-world {
    include wasi:http/proxy@0.2.0;
    
    export lifecycle: interface {
        before-start: func();
        on-started: func();
    }

    import lock: interface {
        lock: func(id: string);
        unlock: func(id: string);
    }
}
